<table id='bpbudget' cellspacing=0 cellpadding=0>
<tr>
<td colspan=5 class="topcellwithmarker">5k</td>
<td colspan=5 class="topcellwithmarker">10k</td>
<td colspan=5 class="topcellwithmarker">15k</td>
<td colspan=5 class="topcellwithmarker">20k</td>
<td colspan=5 class="topcellwithmarker">25k</td>
<td colspan=5 class="topcellwithmarker">30k</td>
<td colspan=5 class="topcellwithmarker">35k</td>
<td colspan=5 class="topcellwithmarker">40k</td>
<td colspan=5 class="topcellwithmarker">45k</td>
<td colspan=5 class="topcellwithmarker">50k</td>
<td colspan=5 class="topcellwithmarker">55k</td>
</tr>
<tr>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlefilled"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
<td class="middlecell"></td>
</tr>
<td colspan=18 class="bottomcellwithmarker">
 Location Rental, Power, Basic Infrastructure, Security, Tables and Chairs, Garbage removal,
   Equipment transport, Location Insurance<br>
   (Breakpoint 09 takes place)
</td>
<td colspan=7 class="bottomcellwithmarker">
Bigscreen and PA<br>
(Enjoyable competition experience)
</td>
<td colspan=3 class="bottomcellwithmarker">
Party shuttle service
</td>
<td colspan=2 class="bottomcellwithmarker">
Party net- work
</td>
<td colspan=2 class="bottomcellwithmarker">
Se- cond stage<br>
(DJ acts)
</td>
<td colspan=4 class="bottomcellwithmarker">
Party tent<br>
(Boozing)
</td>
<td colspan=2 class="bottomcellwithmarker">
Comp- etition video reco- rding<br>
</td>
<td colspan=2 class="bottomcellwithmarker">
Party theme deco- ration
</td>
<td colspan=3 class="bottomcellwithmarker">
Music liveacts
</td>
<td colspan=10 class="bottomcellwithmarker">
Competition prizes
</td>
<td colspan=2 class="bottomcellwithmarker">
Party video strea- ming
</td>
</tr>
</table>
